name: Build Tetris


on:
  push:
    paths-ignore: ["**.md", "LICENSE"]
  pull_request:
    paths-ignore: ["**.md", "LICENSE"]



jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: build jar
        run: mvn clean package

      - name: copy runtime and dependencies
        run: mvn dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=deps

      - name: jlink
        shell: cmd
        run: |
          jlink ^
            --module-path "%JAVA_HOME%\jmods;deps" ^
            --add-modules javafx.controls,javafx.fxml ^
            --output runtime ^
            --strip-debug ^
            --compress=2 ^
            --no-header-files ^
            --no-man-pages

      - name: jpackage
        shell: cmd
        run: |
          jpackage ^
            --name Tetris ^
            --input target ^
            --main-jar Tetris.jar ^
            --main-class davidsoliar.tetris.App ^
            --runtime-image runtime ^
            --icon src/main/resources/images/icon.ico ^
            --type app-image ^
            --dest dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tetris-Windows
          path: dist
